name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup QEMU Emulator
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
    - name: Setup Docker Buildx Command
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-shanghai.aliyuncs.com
        access-key-id: "${{ secrets.ALIYUN_AK }}"
        access-key-secret: "${{ secrets.ALIYUN_SK }}"
    - name: Build and push image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t registry.cn-shanghai.aliyuncs.com/dianhsu/cloudreve:latest .
        docker push registry.cn-shanghai.aliyuncs.com/dianhsu/cloudreve:latest
